### ISSUE TITLE
Consultation of TensorFlow and CuDNN version used in the project

### ISSUE THREAD

**Issue by QDZ123** [interactionlab/PalmTouch#2]
The work of PalmTouch is such an brilliant work that has inspired me a lot, but there are problems having been confusing me in the process of trying to reproduce PalmTouch.

Due to the requirements of the `tf.contrib` library, which is said to be only included in TensorFlow 1.x, I have been trying to use tf 1.x, but it doesn't work, with an error saying `Loaded runtime CuDNN library: 7.3.1 but source was compiled with 7.6.0`. It seems there's something wrong with the TensorFlow or CuDNN version. But the matched CuDNN version for tf 1.x should be lower than 7.4, according to [Build from source  | TensorFlow](https://www.tensorflow.org/install/source).
Would you please like to inform me of **the version of TensorFlow, CUDA and CuDNN** used in your model?

Thank you very much for your reading and I am looking forward to your early reply.

**Comment by sven-mayer** [comment]
@QDZ123, it seems that your source version of CuDNN (needed to compile code) is lower than your runtime CuDNN library (needed to run code) and not version 7.6.0 but 7.3.1. Especially concerning to me seems that the compile version is lower than the runtime. This seems to be a major issue. Typically it can be the other way around. But to fix your issue I recommend installing the same versions. 

For installing CuDNN compile version, see: https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html, and the runtime version is typically installed together with the Nvidia drivers (to see the currently installed version use the command `nvidia-smi`)

Finally, I can say it is not a code issue but a local environment issue.
